### ISSUE TITLE
Manage food diary settings

### ISSUE THREAD

**Issue by cherrygoh** [cherrygoh/calorie-counter#2]
As a user, I want to be able to manage my food diary settings so that I can customize my meal times calorie goals, and other nutrition goals.

# Acceptance Criteria
- [ ] User should be able to customize the number and names of meal times they have in a day (refer to #3).
- [ ] User should be able to set their calorie goals (refer to #4).
- [ ] User should be able to set their nutrition goals (refer to #5).
